name = "SevTech Ages"
author = "Darkosto, Firstnecron, RobertDropTable"
version = "3.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31ef99369a0d2d445e18b574677c54e51c41068fe0970ef1ee7ba0c6cef954e0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12.2"]
